  spring:
    data:
      mongodb:
        uri: mongodb+srv://user-node:VjZaVU40auDAQNzF@mycluster.hs7kv.mongodb.net/anagrams
  logging:
    level:
      org:
        springframework:
          boot:
            autoconfigure:
              mongo:
                embedded: off
  server:
    error:
      include-message: always
  springdoc:
    swagger-ui:
      path: /swagger-ui:html